### ISSUE TITLE
Issues with jdk1.7.0_67

### ISSUE THREAD

**Issue by kosmal-certifydata** [michaelrice/WeakSSL#4]
The java.security.Provider class in jdk1.7.0_67 checks to see that any TrustManagerFactorySpi returned by a provider is public (I'm not sure why Oracle added this check.)  This new check causes an exception the SSL context initialization.   The change appears in line 1283 of java.security.Provider class in jdk1.7.0_67.

Using the WeakSSL plugin with the version of the JDK should reproduce the problem.  

Changing the TrustingTrustManagerFactory from protected to public appears to fix the problem.

Thanks!

**Comment by hartsock** [comment]
You've got such detail on that, I wonder why you didn't author a pull request. Want to author a pull request?

Edit: please author a pull request.

**Comment by hartsock** [comment]
Thank you!
